{{- if .Values.capabilities.kubectlProxy.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: komodor-kubectl-proxy-config
data:
  nginx.conf: |
    events {}
    http {
      resolver kube-dns.kube-system.svc.cluster.local valid=10s;

      server {
        listen 443 ssl;
        server_name localhost;

        ssl_certificate     /etc/nginx/ssl/tls.crt;
        ssl_certificate_key /etc/nginx/ssl/tls.key;

        location / {
          proxy_pass https://kubernetes.default.svc.cluster.local;

          # Set correct Host header for API server
          proxy_set_header Host kubernetes.default;

          # Enable SNI for Kubernetes API TLS
          proxy_ssl_server_name on;
          proxy_ssl_name kubernetes.default;

          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

          proxy_set_header X-Forwarded-Proto https;

          # Enable connection upgrade for WebSocket (used by kubectl exec/cp)
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection $http_connection;

          # Disable buffering and force streaming
          proxy_buffering off;
          proxy_cache off;
          proxy_request_buffering off;

          # Allow long-lived connections
          proxy_read_timeout 3600;
        }
      }
    }
{{- end }}
