{{- if .Values.capabilities.networkMapper }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "network.mapper.fullName" . }}
rules:
  - apiGroups:
      - ''
    resources:
      - 'endpoints'
      - 'pods'
    verbs:
      - 'get'
      - 'list'
      - 'watch'
  - apiGroups:
      - ''
    resources:
      - namespaces
    verbs:
      - 'get'
  - apiGroups:
      - 'apps'
    resources:
      - 'deployments'
      - 'daemonsets'
      - 'replicasets'
      - 'statefulsets'
    verbs:
      - 'get'
{{- end }}