{{- if .Values.capabilities.networkMapper }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "network.mapper.fullName" . }}
rules:
  - apiGroups:
      - ''
    resources:
      - 'configmaps'
    resourceNames:
      - {{ template "network.mapper.configMapName" . }}
    verbs:
      - 'get'
      - 'update'
{{- end }}