{{- if and .Values.createRbac (not .Values.rbacLegacyMode) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "komodorAgent.clusterRole.supervisor" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "komodorAgent.clusterRole.supervisor" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "komodorAgent.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
