{{- if and .Values.createRbac (not .Values.rbacLegacyMode) -}}
{{- if .Values.capabilities.nodeEnricher }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "komodorAgent.clusterRole.nodeEnricher" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "komodorAgent.clusterRole.nodeEnricher" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "komodorAgent.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
{{- end -}}
