apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "komodorAgent.fullname" . }}
  labels:
    {{- include "komodorAgent.labels" . | nindent 4 }}
    {{- include "komodorAgent.user.labels" . | nindent 4 }}
  annotations:
    {{ toYaml .Values.components.komodorAgent.annotations | nindent 4 }}
spec:
  replicas: 1
  strategy:
  {{- if not (empty .Values.components.komodorAgent.strategy) }}
    {{- toYaml .Values.components.komodorAgent.strategy | nindent 4 }}
  {{ else }}
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  {{- end }}
  selector:
    matchLabels:
      {{- include "komodorAgent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- if not (empty (((.Values.components).komodorAgent).podAnnotations)) }}
        {{- toYaml .Values.components.komodorAgent.podAnnotations | trim | nindent 8 }}
        {{- end }}
      labels:
        {{- include "komodorAgent.watcher.selectorLabels" . | nindent 8 }}
        {{- include "komodorAgent.user.labels" . | nindent 8 }}
    spec:
      {{ include "komodorAgent.pod.securityContext" . | nindent 6 }}
      priorityClassName: {{ .Values.components.komodorAgent.priorityClassName | default (printf "%s-agent-high-priority" (include "komodor.truncatedReleaseName" .)) }}
      serviceAccountName: {{ include "komodorAgent.serviceAccountName" . }}
      affinity:
        {{- toYaml .Values.components.komodorAgent.affinity | nindent 8 }}
      nodeSelector:
        "kubernetes.io/os": "linux"
        {{- if not (empty (((.Values.components).komodorAgent).nodeSelector)) }}
        {{- toYaml .Values.components.komodorAgent.nodeSelector | nindent 8 }}
        {{- end }}
      tolerations:
        {{- toYaml .Values.components.komodorAgent.tolerations | nindent 8 }}

      initContainers:
        {{- include "ca-init.container" .                   | trim | nindent 8 }}

      containers:
        {{- include "watcher.container" .                   | trim | nindent 8 }}
        {{- include "supervisor.container" .                | trim | nindent 8 }}

      volumes:
        {{- include "agent.deploy.volumes" .                | trim | nindent 8 }}
        {{- include "custom-ca.volume" .                    | trim | nindent 8 }}
        {{- include "custom-ca.trusted-volume" .            | trim | nindent 8 }}
---
{{- if .Values.capabilities.tasks.sandbox.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "komodorAgent.fullname" . }}-sandbox
  {{- with .Values.components.sandbox.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "sandbox.labels" . | nindent 4 }}
    {{- include "sandbox.user.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "sandbox.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sandbox.selectorLabels" . | nindent 8 }}
        {{- include "sandbox.user.labels" . | nindent 8 }}
      {{- with .Values.components.sandbox.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "komodorAgent.serviceAccountName" . }}
      {{- with .Values.components.sandbox.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.components.sandbox.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      nodeSelector:
        "kubernetes.io/os": "linux"
        {{- if not (empty (((.Values.components).sandbox).nodeSelector)) }}
        {{- toYaml .Values.components.sandbox.nodeSelector | nindent 8 }}
        {{- end }}
      {{- with .Values.components.sandbox.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: komodor-agent-sandbox
          image: {{ .Values.components.sandbox.image }}
          imagePullPolicy: {{ .Values.components.sandbox.pullPolicy }}
          command:
            {{- toYaml .Values.components.sandbox.command | nindent 12 }}
          args:
            {{- toYaml .Values.components.sandbox.args | nindent 12 }}
          {{- if or .Values.components.sandbox.env .Values.components.sandbox.extraEnvVars }}
          env:
            {{- range $name, $value := .Values.components.sandbox.env }}
            - name: {{ $name }}
              value: {{ $value | quote }}
            {{- end }}
            {{- with .Values.components.sandbox.extraEnvVars }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- with .Values.components.sandbox.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.components.sandbox.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
