---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ .Release.Name }}-daemon-high-priority
value: 10000000
globalDefault: false
description: "This priority class should be used for Komodor daemonset pods only."

---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ .Release.Name }}-agent-high-priority
value: 10000000
globalDefault: false
description: "This priority class should be used for Komodor agent pods only."