---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ include "komodor.truncatedReleaseName"  . }}-daemon-high-priority
value: {{ .Values.components.komodorDaemon.PriorityClassValue }}
globalDefault: false
description: "This priority class should be used for Komodor daemonset pods only."

---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ include "komodor.truncatedReleaseName"  . }}-agent-high-priority
value: {{ .Values.components.komodorAgent.PriorityClassValue }}
globalDefault: false
description: "This priority class should be used for Komodor agent pods only."
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ include "komodor.truncatedReleaseName"  . }}-metrics-high-priority
value: {{ .Values.components.komodorMetrics.PriorityClassValue }}
globalDefault: false
description: "This priority class should be used for Komodor  pods only."

{{- if .Values.capabilities.admissionController.enabled }}
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ include "komodorAgent.admissionController.priorityClassName"  . }}
value: {{ .Values.components.admissionController.PriorityClassValue }}
globalDefault: false
description: "This priority class should be used for Komodor admission-controller pods only."
{{- end }}