{{- if and ((.Values.capabilities).klaudiaIntegrationSync).enabled (not .Values.publicApiKeySecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "komodorAgent.publicApiKey.secret.name" . }}
type: Opaque
data:
  {{ default "publicApiKey" .Values.publicApiKeySecretKey }}: {{ .Values.publicApiKey | required "publicApiKey is required when a dependent capability is enabled (e.g. capabilities.klaudiaIntegrationSync)" | b64enc }}
{{- end }}
