{{- if not .Values.apiKeySecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "komodorAgent.secret.name" . }}
type: Opaque
data:
  {{ .Values.secretKey }} : {{ .Values.apiKey | required "apiKey is a required value!" | b64enc }}
{{- end }}
