{{- if and .Values.serviceAccount.createDaemonMetrics .Values.createRbac -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "komodorAgent.daemonMetrics.serviceAccountName" . }}
  labels:
    {{- include "komodorAgentDaemon.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
{{- if not (empty .Values.imagePullSecret) }}
imagePullSecrets:
  - name: {{ .Values.imagePullSecret }}
{{- end }}
{{- end }}
