exclusions: # []
  - SystemPath: /usr/bin/watcher
    CVEs:
      - CVE-2024-24790
    Reason: "False alarm by mend scanner"
    MuteUntil: 2024-09-01

  - SystemPath: /bin/custom_input # telegraf custom input plugin
    CVEs:
      - CVE-2024-24790
    Reason: "False alarm by mend scanner"
    MuteUntil: 2024-09-01
