env:
  MEND_URL: "https://saas.whitesourcesoftware.com"
steps:

  - label: "Scan"
    commands:
      - curl https://downloads.mend.io/cli/linux_amd64/mend -o /usr/local/bin/mend && chmod +x /usr/local/bin/mend
      - python3 .buildkite/vulnerability-scan/main.py
    agents:
      builder: "dind"
    plugins:
      - zacharymctague/aws-ssm#v1.0.0:
          parameters:
            MEND_USER_KEY: /mend/USER_KEY
            MEND_EMAIL: /mend/EMAIL

