steps:
  - label: ":microbe: Scan komodor-agent image"
    commands:
      -  .buildkite/vulnerability-scan/scan_image_with_wiz.sh komodor-agent
    agents:
      builder: "non-docker"
    plugins:
      - zacharymctague/aws-ssm#v1.0.0:
          parameters:
            WIZ_CLIENT_ID: /app/ci/wiz/cli/CLIENT_ID
            WIZ_CLIENT_SECRET: /app/ci/wiz/cli/CLIENT_SECRET
            
  - label: ":microbe: Scan telegraf image"
    commands:
      - .buildkite/vulnerability-scan/scan_image_with_wiz.sh telegraf
    agents:
      builder: "non-docker"
    plugins:
      - zacharymctague/aws-ssm#v1.0.0:
          parameters:
            WIZ_CLIENT_ID: /app/ci/wiz/cli/CLIENT_ID
            WIZ_CLIENT_SECRET: /app/ci/wiz/cli/CLIENT_SECRET
