steps:
  - label: ":memo: annotate build"
    command: |
      buildkite-agent annotate --style info "<a href='https://app.wiz.io/findings/code-cicd-scans#%7E%28filters%7E%28timestamp%7E%28inTheLast%7E%28amount%7E30%7Eunit%7E%27days%29%29%7EcicdScanTrigger%7E%28equals%7E%28%7E%27USER_INITIATED%29%29%7EfindingType%7E%28equals%7E%28%7E%27VULNERABILITY%29%29%7EcicdScanResourceType%7E%28equals%7E%28%7E%27CONTAINER_IMAGE%29%29%29%29'>Wiz scan report</a>"

  - label: ":microbe: Scan komodor-agent image"
    commands:
      -  .buildkite/vulnerability-scan/scan_image_with_wiz.sh komodor-agent
    agents:
      builder: "builder-dind-agent"
    plugins:
      - zacharymctague/aws-ssm#v1.0.0:
          parameters:
            WIZ_CLIENT_ID: /app/ci/wiz/cli/CLIENT_ID
            WIZ_CLIENT_SECRET: /app/ci/wiz/cli/CLIENT_SECRET

  - label: ":microbe: Scan telegraf image"
    commands:
      - .buildkite/vulnerability-scan/scan_image_with_wiz.sh telegraf
    agents:
      builder: "builder-dind-agent"
    plugins:
      - zacharymctague/aws-ssm#v1.0.0:
          parameters:
            WIZ_CLIENT_ID: /app/ci/wiz/cli/CLIENT_ID
            WIZ_CLIENT_SECRET: /app/ci/wiz/cli/CLIENT_SECRET

  - label: ":microbe: Scan admission-controller image"
    commands:
      - .buildkite/vulnerability-scan/scan_image_with_wiz.sh admission-controller
    agents:
      builder: "builder-dind-agent"
    plugins:
      - zacharymctague/aws-ssm#v1.0.0:
          parameters:
            WIZ_CLIENT_ID: /app/ci/wiz/cli/CLIENT_ID
            WIZ_CLIENT_SECRET: /app/ci/wiz/cli/CLIENT_SECRET

  - label: ":microbe: Scan komodor-otel-collector image"
    commands:
      - .buildkite/vulnerability-scan/scan_image_with_wiz.sh komodor-otel-collector
    agents:
      builder: "builder-dind-agent"
    plugins:
      - zacharymctague/aws-ssm#v1.0.0:
          parameters:
            WIZ_CLIENT_ID: /app/ci/wiz/cli/CLIENT_ID
            WIZ_CLIENT_SECRET: /app/ci/wiz/cli/CLIENT_SECRET

  - label: ":microbe: Scan nginx image"
    commands:
      - .buildkite/vulnerability-scan/scan_image_with_wiz.sh nginx
    agents:
      builder: "builder-dind-agent"
    plugins:
      - zacharymctague/aws-ssm#v1.0.0:
          parameters:
            WIZ_CLIENT_ID: /app/ci/wiz/cli/CLIENT_ID
            WIZ_CLIENT_SECRET: /app/ci/wiz/cli/CLIENT_SECRET
