apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-watcher.name" . }}-config
  namespace: {{ default .Release.Namespace .Values.namespace }}
data:
  komodor-k8s-watcher.yaml: |
{{- include "watcher.values" . | nindent 4 }}