apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-watcher.name" . }}-config
  namespace: {{ include "namespace" . }}

data:
  clusterName: {{ .Values.watcher.clusterName | required "watcher.clusterName is a required value!" }}
  komodor-k8s-watcher.yaml: |
{{- include "watcher.values" . | nindent 4 }}

    