apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-watcher.name" . }}-config
data:
  clusterName: {{ .Values.clusterName | required "clusterName is a required value!" }}
  komodor-k8s-watcher.yaml: |
    {{- include "watcher.values" . | nindent 4 }}
  installed-values.yaml: |
    {{ toYaml .Values | nindent 4 }}   