steps:
  - input: "RC Tag"
    fields:
      - select: "Stream"
        key: "rc-tag"
        required: true
        hint: Select RC tag to check and release as GA
        options: []

  - input: "Job Mode"
    fields:
      - select: "Stream"
        key: "job-mode"
        required: true
        default: "ga"
        hint: "GA: Check the version before releasing as GA,\nHOTFIX: Skip stability checks and just release the version"
        options:
          - label: "GA"
            value: "ga"
          - label: "Hotfix"
            value: "hotfix"

  - wait

  - label: ":console: Agent dashboard"
    command: |
      buildkite-agent annotate '*[Monitoring dashboard](https://app.datadoghq.com/dashboard/j69-vt8-tfq/komodor-agent-troubleshooting-dashboard?refresh_mode=sliding&tpl_var_accountname%5B0%5D=helm-chart-test&tpl_var_clustername%5B0%5D=komodor-agent-%2A)*' --style 'info' --context 'ctx-agent-dashboard'

  - label: ":new: Setup cluster & run scenarios"
    commands:
      - cd .buildkite/release_checks
      - komo ci docker-login
      - echo $$SA_KEY > sa.json

      - ./ci.sh
    env:
      RUN_TIMEOUT: 60m
    retry:
      manual:
        permit_on_passed: true
    agents:
      builder: "dind"
    plugins:
      - zacharymctague/aws-ssm#v1.0.0:
          parameters:
            SA_KEY: /app/ci/gcp/AGENT_RELEASE_SA_KEY
            AGENT_API_KEY: /helm-chart-test/production/API_KEY

  - wait

  - input: "Version increment type"
    fields:
      - select: "Stream"
        key: "version-type"
        default: "patch"
        required: true
        options:
          - label: "Major"
            value: "major"
          - label: "Minor"
            value: "minor"
          - label: "Patch"
            value: "patch"

  - wait

  - label: ":new: Release new charts"
    trigger: "helm-charts"
    build:
      message: "${BUILDKITE_MESSAGE}"
      commit: "${BUILDKITE_COMMIT}"
      branch: "${BUILDKITE_BRANCH}"
      env:
        PARENT_JOB_ID: "${BUILDKITE_JOB_ID}"
