steps:
  - command: helm template k8s-watcher charts/k8s-watcher -f charts/k8s-watcher/values.yaml --set apiKey="sanity"
    label: "helm template check for sanity"
  - wait

  - block: "Bump Versions"
    branches: master
  - commands:
      - "git config user.email buildkite@users.noreply.github.com"
      - "git config user.name buildkite"
      - git fetch --tags
      - git checkout master
      - APP_VERSION=$(buildkite-agent meta-data get "version" --job ${PARENT_JOB_ID} || true)
      - if [ -z "$$APP_VERSION" ]; then APP_VERSION=$(cat charts/k8s-watcher/Chart.yaml | grep 'appVersion:' | awk '{print \$2}'); fi
      - echo "Updating app version to $$APP_VERSION"
      - "sed -i -e \"s/appVersion.*/appVersion: $$APP_VERSION/g\" charts/k8s-watcher/Chart.yaml"
      - CURRENT_VERSION=$(cat charts/k8s-watcher/Chart.yaml | grep 'version:' | awk '{print \$2}')
      - NEW_VERSION=$(echo $$CURRENT_VERSION | awk -F. '{\$NF = \$NF + 1;} 1' | sed 's/ /./g')
      - echo "Updating chart version from $$CURRENT_VERSION to $$NEW_VERSION"
      - "sed -i -e \"s/$$CURRENT_VERSION/$$NEW_VERSION/g\" charts/k8s-watcher/Chart.yaml"
      - "buildkite-agent meta-data set \"version\" \"$$NEW_VERSION\""
      - "git add charts/k8s-watcher/Chart.yaml"
      - "git commit -m \"[skip ci] increment chart versions\" || echo \"Already up-to-date\""
      - "git push -f || echo \"Nothing to push!\""
    label: Bump Versions
    key: bump-versions
    branches: master
  - wait

  - block: "release helm chart"
    branches: master
  - label: Publish Helm charts to Github Pages
    env:
      - GITHUB_PAGES_REPO: "komodorio/helm-charts"
      - BRANCH: $BUILDKITE_BRANCH
    commands:
      - APP_VERSION=$(buildkite-agent meta-data get "version" --job ${PARENT_JOB_ID} || true)
      - if [ -z "$$APP_VERSION" ]; then APP_VERSION=$(cat charts/k8s-watcher/Chart.yaml | grep 'appVersion:' | awk '{print \$2}'); fi
      - "sed -i -e \"s/appVersion.*/appVersion: $$APP_VERSION/g\" charts/k8s-watcher/Chart.yaml"
      - NEW_VERSION=$(buildkite-agent meta-data get "version")
      - "sed -i -e \"s/version.*/version: $$NEW_VERSION/g\" charts/k8s-watcher/Chart.yaml"
      - make generate-kube
      - cd manifests/base
      - kustomize edit set image komodorio/k8s-watcher=komodorio/k8s-watcher:$$APP_VERSION
      - kustomize edit set label app.kubernetes.io/watcher-version:$$APP_VERSION
      - cd ../..
      - "GITHUB_PAGES_REPO=komodorio/helm-charts sh publish.sh"
    branches: master
    depends_on: "bump-versions"
  - wait

  - commands:
      - echo "Waiting for repository to be updated before checking"
      - sleep 15
      - helm repo add komodorio https://helm-charts.komodor.io
      - helm repo update
      - helm repo list
      - helm show all komodorio/k8s-watcher
    branches: master
    label: "release to helm chart version to github pages"
  - wait

  - commands:
      - aws eks --region us-east-1 update-kubeconfig --name main
      - helm repo add komodorio https://helm-charts.komodor.io
      - helm repo update
      - helm upgrade --install mono komodorio/k8s-watcher --set apiKey=$$API_KEY --set watcher.collectHistory=true --set watcher.nameBlacklist="{leader,election}" --set watcher.resources.secret=true --set watcher.redact="{.*KEY.*,.*key.*,.*BUGSNAG.*}" --set watcher.enableAgentTaskExecution=true --set watcher.allowReadingPodLogs=true
    plugins:
      - zacharymctague/aws-ssm#v1.0.0:
          parameters:
            API_KEY: /komodor/production/kubernetes/api-key 
    label: "Install new watcher version on komodor main :kubernetes: cluster"
    branches: master
