imagePullSecret: docker-cfg-komodorio

capabilities:
  event:
    redact: "{.*KEY.*,.*key.*,.*BUGSNAG.*}"
  events:
    create: false
  kubectlProxy:
    enabled: true
  admissionController:
    enabled: true
    binpacking:
      enabled: true
      markUnevictable: true
      addNodeAffinityToMarkedPods: true
    mutatingWebhook:
      selfManage: true # do not create the mutating webhook configuration since we need to install the agent multiple times it will conflict

allowedResources:
  secret: true

components:
  komodorDaemonWindows:
    tolerations:
      - key: Windows
        operator: Exists
  komodorDaemon:
    tolerations:
      - key: "komodor.io/sensitive"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
  komodorMetrics:
    tolerations:
      - key: "komodor.io/sensitive"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
  komodorAgent:
    watcher:
      extraEnvVars:
        # DD_VERSION + DD_SERVICE is set in the agent already
        - name: "ENABLE_DD_PROFILER"
          value: "true"
        - name: "DD_ENV"
          value: "production"
        - name: "DD_AGENT_HOST"
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP



