apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "otterize.mapper.fullName" . }}-{{ .Release.Name }}
rules:
  - apiGroups:
      - ''
    resources:
      - 'endpoints'
      - 'pods'
    verbs:
      - 'get'
      - 'list'
      - 'watch'
  - apiGroups:
      - 'apps'
    resources:
      - 'deployments'
      - 'daemonsets'
      - 'replicasets'
      - 'statefulsets'
    verbs:
      - 'get'
{{ if or (and (eq .Values.global.allowGetAllResources nil) .Values.allowGetAllResources) .Values.global.allowGetAllResources}}
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - get
      - list
      - watch
{{ end }}
