apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "otterize.mapper.fullName" . }}-{{ .Release.Name }}
  {{- if hasKey .Values "namespace" }}
  namespace: {{ .Values.namespace }}
  {{- end }}
rules:
  - apiGroups:
      - ''
    resources:
      - 'configmaps'
    resourceNames:
      - {{ template "otterize.mapper.configMapName" . }}
    verbs:
      - 'get'
      - 'update'
