apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "otterize.mapper.fullName" . }}-{{ .Release.Name }}
  {{- if hasKey .Values "namespace" }}
  namespace: {{ .Values.namespace }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "otterize.mapper.fullName" . }}-{{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "otterize.mapper.fullName" . }}-{{ .Release.Name }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: {{ template "otterize.mapper.fullName" . }}-{{ .Release.Name }}
          image: "{{ .Values.mapper.repository }}/{{ .Values.mapper.image }}:{{ .Values.mapper.tag }}"
          {{ if .Values.mapper.pullPolicy }}
          imagePullPolicy: {{ .Values.mapper.pullPolicy }}
          {{ end }}
          resources:
            {{- toYaml .Values.mapper.resources | nindent 12 }}
          env:
            - name: OTTERIZE_DEBUG
              value: {{ .Values.debug | quote }}
            {{ if .Values.global.otterizeCloud.apiAddress }}
            - name: OTTERIZE_API_ADDRESS
              value: "{{ .Values.global.otterizeCloud.apiAddress }}"
            {{ end }}
            {{ if .Values.global.otterizeCloud.credentials.clientId }}
            - name: OTTERIZE_CLIENT_ID
              value: "{{ .Values.global.otterizeCloud.credentials.clientId }}"
            {{ end }}
            {{ if .Values.global.otterizeCloud.credentials.clientSecret }}
            - name: OTTERIZE_CLIENT_SECRET
              value: "{{ .Values.global.otterizeCloud.credentials.clientSecret }}"
            {{ end }}
            - name: OTTERIZE_UPLOAD_INTERVAL_SECONDS
              value: {{ .Values.mapper.uploadIntervalSeconds | default "60" | quote }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
      serviceAccountName: {{ template "otterize.mapper.fullName" . }}-{{ .Release.Name }}
