apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: komodor-memory-checker
  labels:
    app.kubernetes.io/name: komodor-memory-checker
    app.kubernetes.io/component: memory-planning
    app.kubernetes.io/part-of: komodor-agent
rules:
- apiGroups: [""] # Core
  resources: ["*"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["*"]
  verbs: ["get", "list"]
- apiGroups: ["extensions"]
  resources: ["*"]
  verbs: ["get", "list"]
- apiGroups: ["networking.k8s.io"]
  resources: ["*"]
  verbs: ["get", "list"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["*"]
  verbs: ["get", "list"]
- apiGroups: ["batch"]
  resources: ["*"]
  verbs: ["get", "list"]
- apiGroups: ["autoscaling"]
  resources: ["*"]
  verbs: ["get", "list"]
- apiGroups: ["policy"]
  resources: ["*"]
  verbs: ["get", "list"]
- apiGroups: ["storage.k8s.io"]
  resources: ["*"]
  verbs: ["get", "list"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list"]
# Argo resources (if available)
- apiGroups: ["argoproj.io"]
  resources: ["*"]
  verbs: ["get", "list"]
# Custom resources - add more as needed
# - apiGroups: ["*"]
#   resources: ["*"]
#   verbs: ["get", "list"]
