{{- define "metrics.container" }}
{{- if ne (.Values.metrics).enabled false }}
- name: metrics
  image: {{ (((.Values).daemon).image).repository | default "public.ecr.aws/komodor-public/telegraf:1.26" }} 
  imagePullPolicy: {{ (((.Values).daemon).image).pullPolicy | default "IfNotPresent" }}
  volumeMounts:
  - name: {{ include "k8s-watcher.name" . }}-metrics-config
    mountPath: /etc/telegraf/telegraf.conf
    subPath: telegraf.conf
  resources:
  {{- if empty ((.Values).daemon).resources }}
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 0.1
      memory: 256Mi
  {{- else }}
    {{- toYaml ((.Values).daemon).resources | nindent 4 }}
  {{- end }}
  envFrom:
  - configMapRef:
      name:  {{ (or .Values.watcher.daemon .Values.watcher.metrics).varsConfigMapName | default "k8s-watcher-daemon-env-vars" }}
  env:
  {{- if .Values.proxy.http }}
  - name: KOMOKW_HTTP_PROXY_URL
    value: {{ .Values.proxy.http }}
  {{- end }}
  {{- if .Values.proxy.https }}
  - name: KOMOKW_HTTPS_PROXY_URL
    value: {{ .Values.proxy.https }}
  {{- end }}
  {{- if .Values.watcher.clusterName }}
  - name: CLUSTER_NAME
    value: {{ .Values.watcher.clusterName }}
  {{- end }}
{{- end }}
{{- end }}

{{- define "metrics.deploy.volumes" }}
{{- if and .Values.metrics (.Values.metrics.enabled | default false) }}
- name: {{ include "k8s-watcher.name" . }}-metrics-config
  configMap:
    name: {{ include "k8s-watcher.name" . }}-metrics-config
{{- end }}
{{- end }}