{{- if ne (.Values.watcher.networkMapper).enable false }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "network.mapper.configMapName" . }}
  namespace: {{ include "namespace" . }}
data: {}
binaryData: {}
{{- end }}