{{- if (.Values.watcher.networkMapper).enable | default true }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "network.mapper.configMapName" . }}
  {{- if hasKey .Values "namespace" }}
  namespace: {{ .Values.namespace }}
  {{- end }}
data: {}
binaryData: {}
{{- end }}