{{- if and .Values.network_mapper (.Values.network_mapper.enabled | default false) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "otterize.mapper.configMapName" . }}
  {{- if hasKey .Values "namespace" }}
  namespace: {{ .Values.namespace }}
  {{- end }}
data: {}
binaryData: {}
{{- end }}