{{- if .Values.serviceAccount.create -}}
{{- if .Values.capabilities.networkMapper }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "network.mapper.fullName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "network.mapper.fullName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "komodorAgent.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "network.mapper.fullName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "network.mapper.fullName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "komodorAgent.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}