{{- if .Values.serviceAccount.create -}}
{{- if ne (.Values.watcher.networkMapper).enable false }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "network.mapper.fullName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "network.mapper.fullName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "k8s-watcher.serviceAccountName" . }}
    namespace: {{ include "namespace" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "network.mapper.fullName" . }}
  namespace: {{ include "namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "network.mapper.fullName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "k8s-watcher.serviceAccountName" . }}
    namespace: {{ include "namespace" . }}
{{- end }}
{{- end }}