{{- if and .Values.network_mapper (.Values.network_mapper.enabled | default false) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "k8s-watcher.serviceAccountName" . }}
  {{- if hasKey .Values "namespace" }}
  namespace: {{ .Values.namespace }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "k8s-watcher.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "k8s-watcher.serviceAccountName" . }}
    {{- if hasKey .Values "namespace" }}
    namespace: {{ .Values.namespace }}
    {{- end }}
{{- end }}