{{- if and .Values.capabilities.admissionController.enabled .Values.components.admissionController.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "komodorAgent.admissionController.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "komodorAgent.admissionController.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.components.admissionController.serviceAccount.annotations | nindent 4 }}
  {{- if not (empty .Values.imagePullSecret) }}
imagePullSecrets:
  - name: {{ .Values.imagePullSecret }}
  {{- end }}
{{- end }} 