{{- if .Values.capabilities.metrics }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "komodorAgent.name" . }}-daemon-windows-config
data:
  telegraf.conf: |
    [agent]
      precision = "${INTERVAL}"
      interval = "${INTERVAL}"
      flush_interval = "${FLUSH_INTERVAL}"

    [[outputs.http]]
      url = {{ include "metrics.collector.endpoint" . | quote}}
      timeout = "${OUTPUT_TIMEOUT}"
      content_encoding = "gzip"
      {{- if .Values.proxy.https }}
      http_proxy_url = "${KOMOKW_HTTPS_PROXY}"
      {{- else if .Values.proxy.http }}
      http_proxy_url = "${KOMOKW_HTTP_PROXY}"
      {{- end }}
      [outputs.http.headers]
        X-ACCOUNT-ID = "${ACCOUNT_ID}"
        X-CLUSTER-NAME = "${CLUSTER_NAME}"
        X-OS-TYPE = "${OS_TYPE}"

    [[inputs.execd]]
      command = ["C:/telegraf/custom_input.exe", "-config", "C:/telegraf/plugin.conf"]
      namedrop = ["kubernetes_system_container"]
      fieldinclude = ["resource_requests_millicpu_units","resource_limits_millicpu_units","resource_requests_memory_bytes","resource_limits_memory_bytes", "capacity_cpu_cores", "capacity_millicpu_cores", "capacity_memory_bytes", "restarts_total", "memory_usage_bytes", "cpu_usage_nanocores", "memory_working_set_bytes", "allocatable_millicpu_cores", "allocatable_memory_bytes"]
      [inputs.execd.tags]
      measure_type = "consolidated"

  plugin.conf: |
    [[inputs.kube_consolidated]]
      bearer_token = "C:/var/run/secrets/kubernetes.io/serviceaccount/token"
      insecure_skip_verify = true
      url = {{ .Values.communications.apiServerUrl | quote }}
      url_kubelet = "https://$NODE_IP:10250"
      namespace = ""
      poll_interval = "${INTERVAL}"

      resource_include = [ "pods", "nodes" ]
      interval = "${INTERVAL_INVENTORY}"
      flush_interval = "${FLUSH_INTERVAL_INVENTORY}"
      inventory_cache_ttl = "${FLUSH_INTERVAL_INVENTORY}"
      owner_cache_ttl = "${FLUSH_INTERVAL_INVENTORY}"
      node_name = "${NODE_NAME}"

{{- end }}
