apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: network-mapper-YOUR_CLUSTER_NAME
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: network-mapper-YOUR_CLUSTER_NAME
subjects:
  - kind: ServiceAccount
    name: k8s-watcher
    namespace: {{ include "namespace" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: network-mapper-YOUR_CLUSTER_NAME
  namespace: {{ include "namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: network-mapper-YOUR_CLUSTER_NAME
subjects:
  - kind: ServiceAccount
    name: k8s-watcher
    namespace: {{ include "namespace" . }}
---
