apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-watcher-daemon-config
  namespace: {{ include "namespace" . }}
data:
  telegraf.conf: |
    [global_tags]
      account_id = "${ACCOUNT_ID}"
      cluster_name = "${CLUSTER_NAME}"

    [agent]
      interval = "${INTERVAL}"
      flush_interval = "${FLUSH_INTERVAL}"

    [[outputs.http]]
      url = "https://app.komodor.com/metrics-collector/api/v1/collect"
      timeout = "${OUTPUT_TIMEOUT}"
      content_encoding = "gzip"
      [outputs.http.headers]
        X-ACCOUNT-ID = "${ACCOUNT_ID}"

    [[inputs.kubernetes]]
      url = "https://$NODE_IP:10250"
      bearer_token = "/run/secrets/kubernetes.io/serviceaccount/token"
      insecure_skip_verify = true
      fieldpass = ["memory_usage_bytes","cpu_usage_nanocores"]
      namedrop = ["kubernetes_system_container"]
      [inputs.kubernetes.tags]
        measure_type = "usage"
---
